// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFk690cBhR5s9zWJ6PlF9gliS3d8XS5p4',
    appId: '1:455389511965:web:2c240132276d9f7f32e1f4',
    messagingSenderId: '455389511965',
    projectId: 'mymedimap',
    authDomain: 'mymedimap.firebaseapp.com',
    storageBucket: 'mymedimap.firebasestorage.app',
    measurementId: 'G-MDR1GSBGX0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjSxr8zNL9gU55pXgj_vTpgiaXoTigREQ',
    appId: '1:455389511965:android:3494044d94d2625632e1f4',
    messagingSenderId: '455389511965',
    projectId: 'mymedimap',
    storageBucket: 'mymedimap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAikcs1Aojmk-jLq1tjakJkdUDqGbRwXag',
    appId: '1:455389511965:ios:cffa0de71109205032e1f4',
    messagingSenderId: '455389511965',
    projectId: 'mymedimap',
    storageBucket: 'mymedimap.firebasestorage.app',
    iosBundleId: 'com.example.mymedimap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAikcs1Aojmk-jLq1tjakJkdUDqGbRwXag',
    appId: '1:455389511965:ios:cffa0de71109205032e1f4',
    messagingSenderId: '455389511965',
    projectId: 'mymedimap',
    storageBucket: 'mymedimap.firebasestorage.app',
    iosBundleId: 'com.example.mymedimap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFk690cBhR5s9zWJ6PlF9gliS3d8XS5p4',
    appId: '1:455389511965:web:854817861bd7703932e1f4',
    messagingSenderId: '455389511965',
    projectId: 'mymedimap',
    authDomain: 'mymedimap.firebaseapp.com',
    storageBucket: 'mymedimap.firebasestorage.app',
    measurementId: 'G-JXX9F7LB4B',
  );

}